In [2]:
import numpy as np

## Basic

### Declaration

In [3]:
a0 = np.fromstring(input(), dtype=int, sep=" ")
a1 = np.zeros((3, 4))
a2 = np.ones((4, 2), int)
a3 = np.array([2, 13, 4, 9])
a4 = np.array([[2, 13, 4, 9]])
a5 = np.arange(1.00, 2.00, 0.01)
a6 = np.identity(10)
a7 = np.ndarray((10, 7), float)

### Simple Arithmetric

In [11]:
a1 = [  [[1, 2], [3, 4]],
        [[5, 6], [7, 8]] ]

print( np.sum(a1) ) # Get sum of all elements
print( np.sum(a1, axis=0) ) # axis = 0 -> down, 1 -> left, 2 -> depth

print( np.sum(a1) ) # Get sum of all elements
print( np.prod(a1) ) # Get product of all elements
print( np.min(a1) )

36
[[ 6  8]
 [10 12]]
36
40320
1


## Shape

In [4]:
def number_of_rows(M):
    return M.shape[0]
    
def number_of_cols(M):
    return M.shape[1]

### Triangle Shape

In [16]:
arr = np.arange(1, 10).reshape(3, 3)
print( np.tril(arr) )
print( np.triu(arr) )

[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


### Transpose

In [5]:
def transpose(A):
    return A.reshape((1, A.shape[0])).T

arr = [1, 2, 3]
print( transpose(np.array(arr)) )
print( arr[:, None] )

array([[1],
       [2],
       [3]])

### Read from string

In [6]:
# R, C = list(map(int, input().split()))
# A = np.zeros((R, C), int)
# for r in range(R):
#     A[r] = np.fromstring(input(), dtype=int, sep=" ")
# A

### Index and Slicing

In [7]:
A = np.arange(0, 20).reshape((4, 5))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
r, c = A.shape
a0 = A[A.shape[0] - 1, A.shape[1] - 1]
a1 = A[:: 2]
a2 = A[::, 1::2]
a3 = A[0, ::2]
a4 = A[1::2, 1]
a5 = A[:r//2, :c//2] # Select second quadrant of array
a6 = A[r//2:, c//2:] # Select fourth quadrant of array
a7 = A[ [0, A.shape[0]-1] ] # Select only first row but all columns
a8 = A[ :, [-1, 0]] # Select all row but only first and last column
a9 = A[list(range(0, 4)) + list(range(5, A.shape[0]))]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
# Remove row i and column j from the matrix
def submatrix(M, i, j):
    R = list(range(M.shape[0]))
    C = list(range(M.shape[1]))
    return M[R[:i] + R[i+1: ]][:, C[:j] + C[j+1:]]
submatrix(np.array([[1,2,3,4],[5,6,7,8],[4,3,2,1],[8,7,6,5]]), 1, 2)

array([[1, 2, 4],
       [4, 3, 1],
       [8, 7, 5]])

### Get index of all minimum elements

In [13]:
arr = np.array([0, 1, 2, 1, 2, 3, 0, 7, 0])
print(np.where(arr == arr.min())[0])

[0 6 8]
